
import type { Metadata } from "next";
import { Inter, Roboto_Mono } from "next/font/google";
import "./globals.css";
import { APP_NAME } from '@/constants';
import { Navbar } from "@/components/Navbar";
import { Footer } from "@/components/Footer";
import { SocialFloatingButtons } from "@/components/SocialFloatingButtons";
import { CartFlyAnimation } from "@/components/CartFlyAnimation";

// Cấu hình font Inter (thay thế cho Geist Sans)
const inter = Inter({
    variable: "--font-geist-sans", // Giữ nguyên tên biến CSS để không làm hỏng file globals.css
    subsets: ["latin", "vietnamese"], // Inter hỗ trợ tốt subset này
    display: "swap",
});

// Cấu hình font Roboto Mono (thay thế cho Geist Mono)
const robotoMono = Roboto_Mono({
    variable: "--font-geist-mono", // Giữ nguyên tên biến CSS
    subsets: ["latin", "vietnamese"],
    display: "swap",
});

export const metadata: Metadata = {
    title: APP_NAME,
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="vi" className="mdl-js">
            <body style={{ fontFamily: 'var(--font-geist-sans), Arial, sans-serif' }} className={`${inter.variable} ${robotoMono.variable} antialiased`}>
                <div className="flex flex-col min-h-screen">
                    <Navbar />
                    <CartFlyAnimation />

                    <main className="flex-grow">
                        {children}
                    </main>

                    <Footer />
                    <SocialFloatingButtons />
                </div>
            </body>
        </html>
    );
}